### ISSUE TITLE
Crashes when you run it. something to do with firebase

### ISSUE THREAD

**Issue by mijiga** [sevenreup/health-covid-android#2]
E/AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
    Process: com.skybox.seven.covid, PID: 27151
    java.lang.IllegalArgumentException: Missing either @POST URL or @Url parameter.
        for method RetrofitService.pushToken
        at retrofit2.Utils.methodError(Utils.java:53)
        at retrofit2.Utils.methodError(Utils.java:43)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:197)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:192)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy0.pushToken(Unknown Source)
        at com.skybox.seven.covid.firebase.FirebaseMessagingService.registerToServer(FirebaseMessagingService.java:40)
        at com.skybox.seven.covid.firebase.FirebaseMessagingService.onNewToken(FirebaseMessagingService.java:33)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.4:108)
        at com.google.firebase.messaging.zzh.run(com.google.firebase:firebase-messaging@@20.1.4:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

**Comment by sevenreup** [comment]
I fixed it, i forgot to add a url to retrofit service.. pul from mster
